### ISSUE TITLE
Material

### ISSUE THREAD

**Issue by CaptainSifff** [DE-RSE/learn-and-teach#2] opened 2023-12-04 16:29 UTC
I found something that might be useful:
https://aisel.aisnet.org/wi2022/sustainable_it/sustainable_it/2/

**Comment by CaptainSifff** [comment] 2023-12-05 11:59
More MAterial:
https://zenodo.org/records/8324828

**Comment by CaptainSifff** [comment] 2023-12-11 23:49
another list:   https://github.com/practical-tutorials/project-based-learning

**Comment by MakisH** [comment] 2023-12-15 14:57
Yet another list, which took over the nice name first: https://github.com/hifis-net/awesome-rse-education, linked from https://github.com/hifis-net/awesome-rse

I am wondering if it makes sense to [start yet another standard](https://xkcd.com/927/)

**Comment by MakisH** [comment] 2024-01-19 15:28
It would be great help to start if everyone could give one resource about each pillar:

- Software Engineering
- Research skills
- Communication/team skills

Please describe why a resource is good and which skills one could learn from there (roughly), relating to the competencies in the paper.

Let's get a first batch till **February 2**.

**Comment by MakisH** [comment] 2024-01-19 16:46
Let me start with an example.

## Software Engineering skills: [Research Software Engineering with Python](https://merely-useful.tech/py-rse/index.html)

This is an ebook that one can read from front to back, covering the shell and CLI tools, Git basics, Makefiles, Configuration files, as well as a bit of Teamwork, Testing, Error-Handling, and Packaging. The level is mostly basic (also for people that have barely any previous experience with programming), but covers a wide range of essential skills.

Skill codes from the paper:
- Covered: DOCBB, LIBS, SWREPOS, SRU, TEAM, PM
- Kind-of covered: MOD, SP, USERS
- Not covered at all: NEW, RC, DOMREP, TEACH, 

Notes: This has not much to do with Python and Python is not required.

## Research skills: [Nature Masterclasses](https://masterclasses.nature.com/catalogue/24073606)

This is a video series discussing topics from academic writing and analyzing data, planning and performing experiments and data collections, managing data, leading, or planning a career in research. Available through university libraries.

Skill codes:
- Covered: RC, PM
- Kind-of covered: USERS, ??? SRU, SP, DOMREP ??? Not sure how to even acquire the NEW.
- Not covered at all: DOCBB, LIBS, SWREPOS, SRU, TEAM, MOD, TEACH

Notes: I have not yet used this resource, but the table of contents sounds like something I wish I had discovered early in my PhD, when I had more time to read and watch such material. I still hope to follow some of these courses eventually.

## Communication skills: [Julia Evans - Help! I have a manager!](https://wizardzines.com/zines/manager/)

This is a (paid) zine, discussing how to communicate with your manager (here: postdoc/professor). How to set clear expectations, ask and process feedback, and how to keep conversations constructive.

Skill codes from the paper:

- Covered: USERS
- Kinda covered: TEAM, TEACH, PM
- Not covered: DOCBB, LIBS, SWLC, SWREPOS, MOS, NEW, RC, SRU, SP, DOMREP

Notes:

Other zines in this series cover a plethora of technical/software engineering skills, such as Bash, Git, Debugging, and more, giving a good overview and showcasing some more advanced tools.

## Further impulses

- Chase Million: [My Reading List for Research Software Engineers](https://bssw.io/blog_posts/my-reading-list-for-research-software-engineers), BSSw.io

**Comment by CaptainSifff** [comment] 2024-01-23 16:33
Let's start one by one:
Software Engineering skills: 
[Solid Principles](https://en.wikipedia.org/wiki/SOLID)
The solid principles are covered in multiple resources from the clean code community.
What to me sounded the most applicable things were the SOLID principles,
where the C++ community has some nice [videos](https://www.youtube.com/watch?v=Ntraj80qN2k)
As one principle that I find universally applicable from the set of SOLID principles(all of them are to varying degree)
is the Single Responsibility Principle, to which this [video ](https://www.youtube.com/watch?v=glYq-dvgby4) invest almost half his time of his keynote talk. Tony has also coined the nice moniker for it, the "KYSS" principle: Keep Your Stuff Separate.

Skill codes from the paper:

Covered: DOCBB, LIBS, SRU, TEAM, MOD, USERS
Not covered at all: NEW, RC, DOMREP, TEACH, PM, SP

**Comment by CaptainSifff** [comment] 2024-01-23 17:02
Research Skills:
### Good Scientific practice:

[DFG Codex](https://www.dfg.de/en/principles-dfg-funding/basics-and-principles-of-funding/good-scientific-practice)
[SWC Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view)

Covered: RC, SRU, TEAM, TEACH, SP, USERS

**Comment by samumantha** [comment] 2024-01-24 05:57
**[CodeRefinery](https://coderefinery.org/)**

Project currently funded by Nordic e- infrastructure collaboration. RSE network/community and workshops with public and mainly self-learning ready materials. General workshop and materials topics (programming language agnostic; but introduces some specific tools in hands-on materials): Intro to and collaborative git, reproducible research, social coding, documentation, jupyter, automated testing and modular code development. Also provides materials on community teaching and instructor training, as well as some other related materials, eg on CMake or data visualization with Python. [All lessons](https://coderefinery.org/lessons/from-coderefinery/)

covered : DOCBB, SWREPOS, SRU, SP, ..?
with instructor training also: TEAM, TEACH, ..?

**Comment by samumantha** [comment] 2024-01-24 06:02
[**Better Scientific Software**](https://bssw.io)

Materials all around writing better scientific software and beyond: https://bssw.io/items

covered: DOCBB, LIBS (?), SWLC (?) , SWREPOS, MOD (?), SRU, SP , TEACH, PM

**Comment by samumantha** [comment] 2024-01-24 06:30
Another porject, similar to CodeRefinery and Bssw: [INTERSECT](https://intersect-training.org)

In addition to their [own materials](https://intersect-training.org/curriculum/) they also provide a list of [other RSE learning materials](https://intersect-training.org/training-links/)

**Comment by samumantha** [comment] 2024-01-24 06:50
Not sure how this fits in here, but it is linked to SRU and SP : Self assessment tool for FAIR research software: https://fairsoftwarechecklist.net/v0.2/

**Comment by samumantha** [comment] 2024-01-24 06:53
Specific to Python but with lots of good general hints too: https://www.pyopensci.org/python-package-guide/index.html
Linking to SP

**Comment by jpthiele** [comment] 2024-01-25 13:46
Sadly somewhat in between SE and R
but the [Good enough practices for scientific computing](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005510) are a nice ressource.

**Comment by jpthiele** [comment] 2024-01-25 13:50
Sadly somewhat in between SE and R
but the [Good enough practices for scientific computing](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005510) are a nice ressource.

**Comment by guadabsb15** [comment] 2024-01-26 08:25
Mostly SE skills but also some Research skills

This O'REILLY book: [Effective Computation in Physics](https://www.oreilly.com/library/view/effective-computation-in/9781491901564/)  is a great resource that in my opinion can be very useful for other fields as well. One of the authors, Kathryn Huff, has contributed and been involved with the carpentries, JOSS ...etc. The topics range from terminal, classes and objects to deploying software, testing, debugging, and copy right. 

skills from paper: DOCBB, LIBS, SWLC, SWREPOS, MOD, SRU, SP,  DOMREP

**Comment by CaptainSifff** [comment] 2024-02-01 19:59
Oh well,
thinking hard about something that I could put under the communication skills, I remembered the [4 hour work week](https://www.amazon.de/4-Hour-Workweek-Expanded-Updated-Cutting-Edge/dp/0307465357) 
I feel this ties in somewhat with PM skills?

The other resource relevant for the TEACHING skill could of course be the [SWC Instructor training](https://carpentries.github.io/instructor-training/)

**Comment by samumantha** [comment] 2024-02-02 07:45
TEACHING, related to above mentioned Carpentries instructor training: [CodeRefinery instructor training](https://coderefinery.github.io/instructor-training/) and built on both there is the [ENCCS - best practices for HPC training](https://enccs.github.io/instructor-training/)

**Comment by CaptainSifff** [comment] 2024-02-02 17:38
I have a strong feeling, that it wouldn't hurt if we mention this: https://www.computer.org/education/bodies-of-knowledge/software-engineering

**Comment by MakisH** [comment] 2024-02-17 17:25
There is now a contributing guide on how to add new resources on the website:
https://github.com/DE-RSE/survey_rse_training/blob/main/CONTRIBUTING.md

I transferred some of the material in the new structure via #11. @CaptainSifff @jpthiele since I did not see any ready-to-copy descriptions and skills for the (very nice) resources you posted, and since I assume you would like to try out the system, I leave transferring your contributions as an exercise to you. :sweat_smile: I have reacted to everything I have already transferred as :eyes:.

Let's try to already transfer everything we have collected here and close this issue. Next contributions can happen directly via PRs (very easy) or individual issues.

**Comment by MakisH** [comment] 2024-02-17 17:28
If we want to link to lists of resources as well, I would make a separate tag for that (maybe a different audience option `meta`). Maybe we could also rename the `audience` to `intent`.

**Comment by MakisH** [comment] 2024-04-17 10:49
Some of the material originally suggested here (by @CaptainSifff and @jpthiele) are still not on the website, but please open separate PRs for that. I am closing this for now, please always open one issue/PR for each resource / group of resources.

**Closed as completed by MakisH** 2024-04-17 10:49 UTC
